export enum GameEvents {
    PLAYER_READY ="game:player_ready",
    ALL_READY = "game:all_ready",
    WORD_INPUT_TURN = "game:word_input_turn", // LO EMITE EL SV PARA AVISAR LA FASE Y A QUIEN LE TOCA
    SUBMIT_WORD = "game:submit_word", // LO EMITE EL JUGADOR
    WORD_SUBMITTED = "game:word_submitted", // LO EMITE EL SV PARA NOTIFICAR LA PALABRA INGRESADA
    DISCUSSION_TURN = "game:discussion_turn", // LO EMITE EL SV Y DSP DE UN TIEMPO EMITE EL VOTE TURN
    VOTE_TURN = "game:vote_turn", // LO EMITE EL SV PARA NOTIFICAR A QUIEN LE TOCA VOTAR
    SUBMIT_VOTE = "game:submit_vote", // LO EMITE CADA JUGADOR AL VOTAR
    VOTE_SUBMITTED = "game:vote_submitted", // LO EMITE EL SV PARA NOTIFICAR EL VOTO DE LOS JUGADORES Y PODER MOSTRAR EL CONTEO
    EXECUTED_PLAYER = "game:executed_player", // LO EMITE EL SV AL RECIBIR SUBMIT VOTE DE TODOS, CALCULA EL EJECUTADO Y LO NOTIFICA
    END_GAME = "game:end_game" // SI EL EL EXECUTED PLAYER ES EL IMPOSTOR, EMITE ESTE
}